### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by jeremymarc** [ariiiman/copper-front#1]
I think the repository is missing some configuration files (/config/).

After running ``` yarn run dev```:
```Error: Cannot find module './config/ip.js'```

**Comment by ariiiman** [comment]
Yes, sorry Jérémy.
I still have to add some files but I'm busy busy.
(look at the .gitignore file)

**Comment by jeremymarc** [comment]
I've seen the ignore file (ip.conf etc). No worries 👍
